version: '3.9'

services:
  events-api:

    build:
      context: ../../
      dockerfile: Infrastructure/Api/Dockerfile

    container_name: events-api

    restart: unless-stopped

    ports:
      - "8081:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__DefaultConnection: "server=events-mysql;port=3306;database=events_db;user=events_user;password=events_pass"

      Redis__ConnectionString: "events-redis:6379"

      Minio__Endpoint: "events-minio:9000"
      Minio__AccessKey: "admin"
      Minio__SecretKey: "admin123456"
      Minio__UseSSL: "false"

    networks:
      - tickets-network

networks:
  tickets-network:
    external: true