version: '3.9'

services:
  minio:
    image: minio/minio

    container_name: events-minio

    restart: unless-stopped

    command: server /data --console-address ":9001"

    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    volumes:
      - minio_data:/data

    networks:
      - tickets-network

volumes:
  minio_data:

networks:
  tickets-network:
    external: true